import {Metadata} from 'next'
export const metadata:Metadata = {
  title: {
     absolute:"",
     default:'NextJS',
     template:"%s | athar",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout ({children}:{children:React.ReactNode}){
return(
  <html>
    <body>
      <header style={{backgroundColor:"red"}}>
        <h1>header</h1>
      </header>
      
        {children}
      
      <footer style={{backgroundColor:"blue"}}>
        <h1>footer</h1>
      </footer>
    </body>
  </html>
)
}
